# # -*- coding: utf-8 -*-
# """Copy of Big cats Transfer learning

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/10erm7xZyBQviwJ7FqtwwB5iUyNv-GvFf
# """

# import os

# os.environ['KAGGLE_USERNAME'] = "ojoolasehindeitunu"  # Replace with your Kaggle username
# os.environ['KAGGLE_KEY'] = "b62a374779fdc4545168d958ca11c737"  # Replace with your Kaggle API key

# from kaggle.api.kaggle_api_extended import KaggleApi

# api = KaggleApi()
# api.authenticate()

# # Download dataset
# dataset_name = "patriciabrezeanu/big-cats-image-classification-dataset"  # Update with your dataset
# api.dataset_download_files(dataset_name, path="./", unzip=True)

# # import kagglehub
# # patriciabrezeanu_big_cats_image_classification_dataset_path =
# # kagglehub.dataset_download('patriciabrezeanu/big-cats-image-classification-dataset')

# # print('Data source import complete.')
# # !ls -l

# # Commented out IPython magic to ensure Python compatibility.
# # Importing libraries

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import matplotlib.pylab as pyl
# import seaborn as sns

# # %matplotlib inline

# from glob import glob
# import cv2
# import os
# import shutil
# import math
# from sklearn.utils import shuffle
# from random import randint

# """#### Data extraction and preparation"""

# def get_images(directory):
#     Images = []
#     Labels = []
#     label = 0

#     for labels in os.listdir(directory): #Main Directory where each class label is present as folder name.
#         if labels == 'cheetah': #Folder contain Glacier Images get the '2' class label.
#             label = 0
#         elif labels == 'leopard':
#             label = 1
#         elif labels == 'lion':
#             label = 2
#         elif labels == 'tiger':
#             label = 3

#         for image_file in os.listdir(directory+labels): #Extracting the file name of the image from Class Label folder
#             image = cv2.imread(directory+labels+r'/'+image_file) #Reading the image (OpenCV)
#             image = cv2.resize(image,(224,224)) #Resize the image, Some images are different sizes. (Resizing is very Important)
#             Images.append(image)
#             Labels.append(label)

#     return shuffle(Images,Labels,random_state=817328462) #Shuffle the dataset you just prepared.

# Images, Labels = get_images('/content/animals/') #Extract the training images from the folders.

# Images = np.array(Images) #converting the list of images to numpy array.
# Labels = np.array(Labels)

# print("Shape of Images:",Images.shape)
# print("Shape of Labels:",Labels.shape)

# def get_classlabel(class_code):
#     labels = {0:'cheetah', 1:'leopard', 2:'lion', 3:'tiger'}

#     return labels[class_code]

# f,ax = plt.subplots(5,5)
# f.subplots_adjust(0,0,3,3)
# for i in range(0,5,1):
#     for j in range(0,5,1):
#         rnd_number = randint(0,len(Images))
#         ax[i,j].imshow(Images[rnd_number])
#         ax[i,j].set_title(get_classlabel(Labels[rnd_number]))
#         ax[i,j].axis('off')

# """#### Data preprocessing"""

# import keras
# import tensorflow

# from keras.applications.mobilenet import preprocess_input
# from keras.models import Sequential, Model
# from tensorflow.keras.preprocessing.image import ImageDataGenerator
# import keras
# from keras.layers import Flatten, Dense

# # Function to preprocess training data

# def Train_processing(path):
#     image = ImageDataGenerator(zoom_range = 0.2, shear_range = 0.2,
#                                preprocessing_function = preprocess_input,
#                               horizontal_flip = True)
#     Image = image.flow_from_directory(directory = path, target_size = (224,224),
#                                      batch_size = 12, class_mode = 'categorical')
#     return Image

# # Function to preprocess other data sets

# def main_processing(path):
#     image = ImageDataGenerator(preprocessing_function = preprocess_input)
#     Image = image.flow_from_directory(directory = path, target_size = (224,224),
#                                      batch_size = 12, class_mode = 'categorical')
#     return Image

# Image_gen = Train_processing('/content/animals')

# """#### Model importation and modification"""

# from keras.applications.mobilenet import MobileNet

# # Instantiating imported model

# Base_model = MobileNet(input_shape = (224, 224, 3), include_top = False)

# # Model info

# Base_model.summary()

# for i in Base_model.layers:
#     i.trainable = False

# # Adding Flattening and final dense layer to model

# Output = Flatten()(Base_model.output)
# Out = Dense(4, activation = 'softmax')(Output)

# model = Model(Base_model.input, Out)

# # Modified model info

# model.summary()

# # Compiling model

# model.compile(loss = 'sparse_categorical_crossentropy',
#              optimizer = 'rmsprop',
#              metrics = ['accuracy'])

# Image_gen

# # Images.shape
# Labels.shape

# # Fitting model

# hist_=model.fit(Images,Labels,
#                 epochs=100,validation_split=0.2)

# """#### Model evaluation and deployment"""

# H = hist_.history

# H.keys()

# # Accuracy plot
# H = hist_.history
# plt.plot(H['accuracy'], c = 'r')

# # Loss plot

# plt.plot(H['loss'])

# """#### EfficientNetV2"""

# from tensorflow.keras.applications import EfficientNetV2B0, EfficientNetV2S, EfficientNetV2M, EfficientNetV2L

# # Instantiating imported model

# Base_model = EfficientNetV2M(input_shape = (224, 224, 3), include_top = False)

# # Instantiating imported model

# Base_model = EfficientNetV2M(input_shape = (224, 224, 3), include_top = False)

# # Define the model outside the loop/function
# Output = Flatten()(Base_model.output)
# Out = Dense(4, activation = 'softmax')(Output)
# model = Model(Base_model.input, Out)

# # Compiling model
# model.compile(loss = 'sparse_categorical_crossentropy',
#              optimizer = 'rmsprop',
#              metrics = ['accuracy'])

# # Fitting model
# Eff_hist=model.fit(Images,Labels,
#                 epochs=15,validation_split=0.15)

# print(Images.shape, Labels.shape)

# # Accuracy plot
# H = Eff_hist.history
# plt.plot(H['accuracy'], c = 'r')
# plt.plot(H['loss'])
# plt.show()


# import streamlit as st
# from PIL import Image
# import numpy as np
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing.image import img_to_array

# # Label mapping
# LABELS = ['cheetah', 'leopard', 'lion', 'tiger']

# # Load model
# try:
#     model = load_model("Cat_model.keras")  # Ensure this file is in the same dir
#     st.success("✅ Model loaded!")
# except Exception as e:
#     st.error(f"❌ Model failed to load: {e}")
#     st.stop()

# # Streamlit UI
# st.title("🦁 Big Cat Classifier")
# uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

# if uploaded_file:
#     try:
#         # Preprocess image
#         image = Image.open(uploaded_file).convert("RGB")
#         st.image(image, caption="Uploaded Image", use_column_width=True)
        
#         # Resize, normalize, add batch dim
#         image = image.resize((224, 224))
#         img_array = img_to_array(image) / 255.0
#         img_array = np.expand_dims(img_array, axis=0)

#         # Predict
#         pred = model.predict(img_array)
#         class_idx = np.argmax(pred[0])
#         confidence = pred[0][class_idx]

#         st.success(f"**Prediction:** {LABELS[class_idx]} (Confidence: {confidence:.2%})")
    
#     except Exception as e:
#         st.error(f"⚠️ Error: {e}")

    
# # """**Saving model**"""

# # pip install gradio

# # import torch
# # torch.save(model, "model.pth")

# # from google.colab import drive
# # drive.mount('/content/drive')

# # model.save("/content/Cat_model.keras")

# # import gradio as gr
# # import torch
# # from torchvision import transforms
# # from PIL import Image

# # LABELS = ['cheetah', 'leopard', 'lion', 'tiger']

# # # Dummy model for illustration
# # class DummyModel(torch.nn.Module):
# #     def forward(self, x):
# #         return torch.tensor([[0.1, 0.7, 0.2, 0.0]])

# # model = keras.models.load_model("/content/Cat_model.keras")
# # transform = transforms.Compose([
# #     transforms.Resize((224, 224)),
# #     transforms.ToTensor()
# # ])

# # def classify(image):
# #     image = transform(image).unsqueeze(0)
# #     with torch.no_grad():
# #         preds = model(image)
# #     return {LABELS[i]: float(preds[0][i]) for i in range(len(LABELS))}

# # gr.Interface(fn=classify, inputs=gr.Image(), outputs=gr.Label()).launch()



# # !wget -q -nc https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
# # !unzip -o ngrok-stable-linux-amd64.zip
# # !mv -f ngrok /usr/local/bin

# # from google.colab import userdata
# # ngrok_auth = userdata.get('ngrok')

# # !ngrok authtoken {ngrok_auth}

# # !echo "ngrok_authtoken_here" | gcloud secrets versions add ngrok --data-file=-

# # from google.colab import userdata

# # # Safely get your ngrok auth token
# # ngrok_auth = userdata.get('ngrok')  # you store this using Colab's form input or Colab Pro's secret manager

# # # Authenticate ngrok
# # !ngrok authtoken {ngrok_auth}

# # !pip install Flask
# # !pip install flask-ngrok

# # # Start ngrok tunnel to expose port 5000 (Flask default)
# # import subprocess
# # import time

# # # Kill previous ngrok processes if needed
# # !pkill ngrok

# # # Run ngrok in background
# # subprocess.Popen(['ngrok', 'http', '5000'])

# # # Give it a few seconds to spin up
# # time.sleep(5)

# # # import pickle
# # # import Flask
# # # from flask_ngrok import run_with_ngrok
# # # import request
# # # import jsonify

# # # # Save the trained model
# # # pickle.dump(model, open("model.pkl", "wb"))

# # # # Flask app setup
# # # app = Flask(__name__)
# # # run_with_ngrok(app)

# # # @app.route("/predict", methods=["POST"])
# # # def predict():
# # #     data = request.get_json()
# # #     input_data = pd.DataFrame([data])
# # #     prediction = model.predict(input_data)
# # #     return jsonify({"prediction": prediction.tolist()})

# # # if __name__ == "__main__":
# # #     app.run()

# # import requests

# # # Try fetching public URL from ngrok's local API
# # try:
# #     response = requests.get("http://localhost:4040/api/tunnels")
# #     tunnel_info = response.json()
# #     public_url = tunnel_info["tunnels"][0]["public_url"]
# #     print("Public URL:", public_url)
# # except Exception as e:
# #     print("Error fetching ngrok tunnel:", e)

# # import requests
# # import time
# # import os

# # # Start ngrok tunnel to expose port 5000 (Flask default)
# # !pkill ngrok # Kill previous ngrok processes if needed
# # !ngrok http 5000 & # Run ngrok in background

# # # Give it a few seconds to spin up
# # time.sleep(5)

# # # Fetch public URL from ngrok API
# # ngrok_api = 'http://localhost:4040/api/tunnels'

# # # Check if ngrok is running by making a request to its API
# # try:
# #     tunnels = requests.get(ngrok_api).json()
# #     public_url = tunnels['tunnels'][0]['public_url']
# #     print("Public URL:", public_url)
# # except requests.exceptions.RequestException as e:
# #     print(f"Error connecting to ngrok API: {e}")
# #     print("Make sure ngrok is running and accessible on port 4040.")
# #     print("Check the output of the 'ngrok http 5000' command for errors.")
# #     # Exit or handle the error appropriately in your application
# #     # os._exit(1)

# # pip install jsonify

# # # !pip install Flask
# # import pickle
# # import flask # Change 'Flask' to 'flask'
# # from flask_ngrok import run_with_ngrok
# # import requests # Change 'request' to 'requests'
# # import jsonify

# # # Save the trained model
# # pickle.dump(model, open("model.pkl", "wb"))

# # # Flask app setup
# # app = flask.Flask(__name__) # Change 'Flask' to 'flask'
# # run_with_ngrok(app)

# # @app.route("/predict", methods=["POST"])
# # def predict():
# #     data = requests.get_json() # Use 'requests' module for getting JSON data
# #     input_data = pd.DataFrame([data])
# #     prediction = model.predict(input_data)
# #     return jsonify({"prediction": prediction.tolist()})

# # if __name__ == "__main__":
# #     app.run()

# # !pip install -q streamlit

# # Commented out IPython magic to ensure Python compatibility.
# # %%writefile app.py
# # import streamlit as st
# # 
# # st.title("Big Cats Classification")
# # st.write("Welcome to your Big Cat Classifier.")

# # import streamlit as st
# # from PIL import Image
# # import torch
# # from torchvision import transforms

# # # Dummy model placeholder (replace with actual model)
# # class DummyModel:
# #     def __call__(self, x):
# #         return torch.tensor([[0.1, 0.7, 0.2]])

# # # Label map
# # LABELS = ['cheetah', 'leopard', 'lion', 'tiger']

# # model = torch.load("model.pth", weights_only=False)
# # # model.eval()

# # transform = transforms.Compose([
# #     transforms.Resize((224, 224)),
# #     transforms.ToTensor()
# # ])

# # st.title("Big Cat Image Classifier")

# # uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])
# # if uploaded_file:
# #     image = Image.open(uploaded_file).convert("RGB")
# #     st.image(image, caption="Uploaded Image", use_column_width=True)

# #     input_tensor = transform(image).unsqueeze(0)
# #     with torch.no_grad():
# #         output = model(input_tensor)
# #         prediction = LABELS[output.argmax().item()]

# #     st.success(f"Prediction: **{prediction}**")

# # from tensorflow.keras.preprocessing.image import load_img, img_to_array

# # def Image_classes_prediction(path, model):
# #     img = load_img(path, target_size = (224, 224))
# #     in_arr = img_to_array(img)
# #     in_arr = preprocess_input(in_arr)
# #     plt.imshow(in_arr)
# #     in_arr = np.expand_dims(in_arr, axis = 0)

# #     Pred = model.predict(in_arr)
# #     Pred_ = np.argmax(Pred)

# #     if Pred_ == 0:
# #         print('Cheetah')
# #     elif Pred_ == 1:
# #         print('Leopard')
# #     elif Pred_ == 2:
# #         print('Lion')
# #     else:
# #         print('Tiger')

# #     return Pred_

# # Leo = ''
# # Image_classes_prediction(Leo, model)

import streamlit as st
from PIL import Image
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array

# Label mapping
LABELS = ['cheetah', 'leopard', 'lion', 'tiger']

# Load model 
@st.cache_resource  # Cache the model to avoid reloading
def load_cat_model():
    return load_model("./Cat_model.keras")  # ./ indicates same folder

model = load_cat_model()

# Streamlit UI
st.title("🦁 Big Cat Classifier")
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    try:
        # Preprocess image
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Uploaded Image", use_column_width=True)
        
        # Resize, normalize, add batch dim
        image = image.resize((224, 224))
        img_array = img_to_array(image) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        # Predict
        pred = model.predict(img_array)
        class_idx = np.argmax(pred[0])
        confidence = pred[0][class_idx]

        st.success(f"**Prediction:** {LABELS[class_idx]} (Confidence: {confidence:.2%})")
    
    except Exception as e:
        st.error(f"⚠️ Error: {e}")